server:
  port: 8089

spring:
  #  servlet:
  #    multipart:
  #      max-file-size: 10MB
  #      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://us-la-cn2-1.natfrp.cloud:21466/meetup
    username: meetup
    password: Example12345678!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3


  #  mybatis:
  #    configuration:
  #      map-underscore-to-camel-case: false

  redis:
    host: localhost
    port: 6379
    #password:
    client-type: lettuce
#    timeout: 10000ms
#    database: 0
#    lettuce:
#      pool:
#        max-wait: -1ms



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    map-camel-to-underscore: true

springfox:
  documentation:
    swagger-ui:
      enabled: true